add missing bind
This should fix a rarely occurring error:

TypeError: Cannot call method 'soapRequest' of undefined
    at /var/task/node_modules/fuelsdk-node/node_modules/fuel-soap/lib/fuel-soap.js:118:11